version: '3.7'

services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'    
    build:
      context: .
      dockerfile: Dockerfile    
    environment:      
      - ASPNETCORE_ENVIRONMENT=Production                  
      - ASPNETCORE_Kestrel__Certificates__Default__Password=abcd.1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./certs/aspnetapp.pfx:/https/aspnetapp.pfx:ro    
    depends_on:
     - "sqlservercontainer"
    networks:
      - aspnetcoreapp-network

  sqlservercontainer:
    container_name: "sqlservercontainer"
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "abcd.1234"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge